[package]
name = "proc_man"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rusqlite = { version = "0.40", features = ["bundled-full"] }
dirs = "7"
lazy_static = "1"
#print_bytes = { version = "2", features = ["os_str_bytes"] }

[[bin]]
name = "proc_man"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1